### ISSUE TITLE
Support for ignoring default styles completely

### ISSUE THREAD

**Issue by fiznool** [iamacup/react-native-markdown-display#100]
First of all, I'd like to thank you for taking over maintenance of this very useful library. I'm in the process of upgrading an app which hasn't been touched in a couple of years, and migrating from `-renderer` is very straightforward. 🙏 

I've hit upon an issue with the styling system that is in use here. My code makes exclusive use of custom rules, rendering out individual components for each markdown element. Each of these components defines its style internally, with no need for any external style prop. Hence, I'd like for the library to not inject any styles at all, whether they be the default styles or any user-defined ones.

I don't think this is currently possible, since the default styles are [always added to the styling system](https://github.com/iamacup/react-native-markdown-display/blob/master/src/index.js#L41-L78). Would you be willing to expose another prop to prevent any styles from being added at all?

**Comment by fiznool** [comment]
FWIW I'm using the current workaround to nullify all default styles, replacing them with empty equivalents.

``` js
import Markdown, { styles as defaultMarkdownStyles } from 'react-native-markdown-display';
import rules from './rules';

// Create a set of styles that shadow the default styles, effectivelty nullifying them.
const markdownDefaultStylesBlanked = Object.keys(markdownDefaultStyles).reduce(
  (acc, k) => ({
    ...acc,
    [k]: {},
  }),
  {},
);

export default function MarkdownComponent({ content }) {
  return (
    <Markdown rules={rules} style={markdownDefaultStylesBlanked} mergeStyle={false}>
      {content}
    </Markdown>
  );
}
```

**Comment by iamacup** [comment]
Yep, sounds sensible to add it, i am away at the moment but hopefuly Sunday i should be able to :)
