### ISSUE TITLE
Markdown doesn't work properly when fontFamily is provided in styles.

### ISSUE THREAD

**Issue by oleksiipopovych** [iamacup/react-native-markdown-display#109]
Is it possible to use different fontFamily?

**Comment by worstestes** [comment]
@alexeypopovich did you figure this out? I'm running into issues regarding formatting while retaining a certain `fontFamily`

**Comment by oleksiipopovych** [comment]
@worstestes I made it like this:
`const styles = StyleSheet.create({
    body: {
      fontFamily: theme.fontFamily,
    },
    em: {
      fontFamily: theme.fontItalic,
    }};`
And same for headings, links, etc
