### ISSUE TITLE
First paragraph in hierarchy should not have marginTop

### ISSUE THREAD

**Issue by pke** [iamacup/react-native-markdown-display#111]
Since margins do not collapse in RN like they do in web CSS its often introducing little bugs when paragraphs have a `marginTop` of 10 by default. Especially if there is only one paragraph in the rendered hierarchy at that level.
In that case no top margin should be applied (like it would in web CSS).

**Comment by habovh** [comment]
I'd even add that paragraphs should not have a top margin at all. In my opinion, every *block* (as opposed to inline) components should have a bottom margin.

That way, every block handles the margin/separation with the next block, not the previous one. The absence of a previous block (i.e. only one block, or the first block in the hierarchy) would not change the way the current block is laid out.

**Comment by pke** [comment]
I have to agree. In my layout library <Stack> elements only have a bottom margin to space them apart.

**Comment by Rebsos** [comment]
I removed the margins on the first and last paragraph with a wrapper view:

```
<View style={{ marginTop: -10, marginBottom: -10}}>
  <Markdown>...</Markdown>
</View>
```
