### ISSUE TITLE
HTML not rendering 

### ISSUE THREAD

**Issue by alexzobi** [iamacup/react-native-markdown-display#116]
First off, thanks for picking up support where markdown-renderer left off.

I must be missing something simple because I cannot figure this out, even though I've gone through the library code and things seems to look fine. Thanks in advance.

```
import Markdown, { MarkdownIt } from 'react-native-markdown-display';

...

<Markdown
  markdownit={
    MarkdownIt({ html: true, breaks: true })
  }
  rules={rules}
  {...props}
>
  {children}
</Markdown>
```
expected: 
```
<h2>This is the same</h2>
## as this
```
actual:
debugger warning:
```Warning, unknown render rule encountered: html_block. 'unknown' render rule used (by default, returns null - nothing rendered)```

**Comment by HenryDeLange** [comment]
@alexzobi I'm having the same problem now. Did you get it working or find out how to resolve the warning?

**Comment by alexzobi** [comment]
@HenryDeLange nope.

**Comment by HenryDeLange** [comment]
I got rid of the warning (in my case for "html_inlne") by adding the following:
```
rules={{
    html_inline: (node, children, parent, styles) => <Text key={node.key}>{children}</Text>
}}
```
