### ISSUE TITLE
Ordered and unorederd lists are too spaced - how to make them more compact?

### ISSUE THREAD

**Issue by tasn** [iamacup/react-native-markdown-display#117]
As the title says, they are very much too spaced (as you can even see in the example screenshots), and I can't for the life of me, not with rules and not with styles figure out how to fix it.
Can this even be achieved? Thanks!

**Comment by iamacup** [comment]
Have you tried using the debugPrintTree to see which rules you need to change? Perhaps a full code example with the style rules you have tried that are not working that you would expect to work.

**Comment by iamacup** [comment]
take a look at 7.0.0-alpha - i think that might have the changes you want to the styles built in

**Comment by tasn** [comment]
I didn't realise there was a new alpha. Just upgraded and it fixes things, thanks!

Also, thank you for all of your work on this, it's great! :)
