### ISSUE TITLE
bullet_lists don't wrap text on 7.0.0-alpha

### ISSUE THREAD

**Issue by iethree** [iamacup/react-native-markdown-display#120]
In v.7.0.0-alpha, individual bulleted list items will not wrap text onto multiple lines.

6.1.6 | 7.0.0-alpha 
---|---
<img width="357" alt="Screen Shot 2020-10-21 at 12 46 39 PM" src="https://user-images.githubusercontent.com/30528226/96757860-a2f8b900-139b-11eb-8cc0-e0c8470f5d48.png"> | <img width="383" alt="Screen Shot 2020-10-21 at 12 47 28 PM" src="https://user-images.githubusercontent.com/30528226/96757863-a429e600-139b-11eb-86f2-40ba417d2d8a.png">

code
```jsx
<View>
   <Markdown>{description}</Markdown>
</View>
```
Really appreciate this package, thanks so much for maintaining!

**Comment by iamacup** [comment]
@abirchall i think this is why they were wrapped. Do you want to take a stab at fixing?

**Comment by carissacks** [comment]
I'm facing the same issue

**Comment by carissacks** [comment]
I'm facing the same issue. And also really want to thank you for maintaining the repo 🎉

**Comment by abirchall** [comment]
Whoops. Yep. Ironically, I believe the fix would be to remove the wrap style from the bulleted list and ordered list styles. Let me take a look.

**Comment by iamacup** [comment]
There is some comentary here about this behavior (in general): https://github.com/iamacup/react-native-markdown-display/issues/88

**Comment by iamacup** [comment]
7.0.0-alpha.2 on NPM
