### ISSUE TITLE
Rendering embedded media (youtube links)

### ISSUE THREAD

**Issue by bibyzan** [iamacup/react-native-markdown-display#123]
I would like to be able to dynamically render youtube links with (most likely) an embedded web view preview of the youtube video. I know this goes against the whole point of this library trying to be all native, however in my experience I'm not sure there's any other way to make the youtube player work without the web view. For this, I would only want to make the youtube videos call the webview, but still keep the rest of the stuff native.

Is there existing functionality I missed here where I can opt to create a custom renderer for links, and keep the rest of the out of box features?

**Comment by Kobidl** [comment]
There is no official support in MD for YouTube videos.

**Options 1:**
I found this answer:
https://github.com/iamacup/react-native-markdown-display/issues/67#issuecomment-627600933

**Option 2**
I found that what we can do is to use iframe (on web versions).
A workaround for react-native using this library (this will work on video players that support iframe such as youtube):

```
        
const data = `
    <iframe width="560" height="315" src="https://www.youtube.com/embed/pg3EXi5Yydw" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
`

const rules = {
    html_block: (node) => {
        return (
            <WebView style={{ height: 300 }} source={{ html: node.content }} />
        )
    }
}
< MarkDown
    rules={ rules }
    markdownit={ MarkdownIt({ typographer: true, html: true }) }
>
    { data }
</MarkDown >


```

**Comment by bibyzan** [comment]
I managed to get the desired functionality by doing essentially what was done in #67 where I had some other project requirements besides youtube and I used custom rules to override the link rule and using various components like `react-native-youtube-iframe` and `react-native-video` to get deep file content functionality through our custom link renderer like this:
```js
<Markdown style={markdownStyle}
          rules={{
              link: (node, children, parent, styles) => {
                  const {key, attributes: {href}} = node;
                  let title = '';
                  if (node.children.length > 0) {
                      const {content} = node.children[0];
                      title = content;
                  }
                  return (
                      <CustomLinkRenderer {...{key, title}} link={href}/>
                  );
              }
          }}
>
    our text
</Markdown>
```
