### ISSUE TITLE
Does this plugin allows copying content? (selectable)

### ISSUE THREAD

**Issue by darron1217** [iamacup/react-native-markdown-display#126]
Does this plugin allows copying content? (selectable)

**Comment by ghost** [comment]
I'm using it and, as far as I can tell, by default the answer is no. The [source code](https://github.com/iamacup/react-native-markdown-display/blob/master/src/lib/renderRules.js#L66) doesn't include `selectable` when rendering `<Text>` elements. That said, you can [override the rendering rules](https://github.com/iamacup/react-native-markdown-display#rules), passing your own custom components. Doing that, you could add `selectable` to each `<Text>` element the library renders, thus making the text selectable.

**Comment by nabeelpkl** [comment]
any solution for this? @darron1217

**Comment by esalaza** [comment]
You can use the `userSelect` style prop.

In React native [v0.71.0](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0710) that style prop was [added](https://github.com/facebook/react-native/commit/fc42d5bbb9906c37c2f62d26c46f6e3191cccd01) which receives the standard CSS [user-select](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) values, mapping them to `selectable` component prop using the map in that commit ([userSelectToSelectableMap](https://github.com/facebook/react-native/commit/fc42d5bbb9906c37c2f62d26c46f6e3191cccd01#diff-8854d86a25d1052c7f65f4d7235198297464645255149b9700171beb00ca67ecR234)).
