### ISSUE TITLE
ASTNode interface in declaration file lacks a few properties

### ISSUE THREAD

**Issue by zecakeh** [iamacup/react-native-markdown-display#130]
I'm mainly thinking of [`sourceMeta`](https://github.com/iamacup/react-native-markdown-display/blob/50856add637320cb566bcd20a74ef4e91d99bdd4/src/lib/util/tokensToAST.js#L27) that allows Markdown-it plugins to add extra data.

Right now we can use attributes to pass extra data to the render rules, but if we want to reuse the plugin with an HTML renderer, the data shows up on the HTML elements.

Is it an oversight or is there a reason to this?

**Comment by ahkhanjani** [comment]
Added in #132.
