### ISSUE TITLE
Feature Request: Allow for custom components

### ISSUE THREAD

**Issue by chmac** [iamacup/react-native-markdown-display#135]
I'd like to be able to replace the `<Text` component that this package renders, by setting it in just once place.

The backstory is that we're using React Native Elements, and have all our styles setup in that, so if we render its `<Text` instead of the core react-native version, the text is correctly styled.

I'd imagine an API like `components={{Text, ...}}` which would replace all calls to `<Text` with whatever was supplied.

Thanks for this package, and especially for forking & maintaining it, it's a great help to be able to render markdown directly in our app. ❤️

**Comment by RiccardoRomagnoli** [comment]
did this get implemented?
