### ISSUE TITLE
Font family style broken when using body styling rule and others simultaneously in Android Devices

### ISSUE THREAD

**Issue by CXZ7720** [iamacup/react-native-markdown-display#137]
When apply custom font using `body` style rule to apply globally, other rule's fontFamily broken in android device.

I think this is because nested text component styling issue related with https://github.com/facebook/react-native/issues/20398

DebugPrintTree options activated, the example result was like this.

<img width="762" alt="스크린샷 2021-03-16 오전 11 08 31" src="https://user-images.githubusercontent.com/29659112/111245424-f5d35580-8647-11eb-9b9c-9d5f9f54420f.png">

Because of **strong** styled component were nested in default *text* styled component, fontFamily doesn't apply to children component.

**[ENV]**
RN 0.64.3
Device : Android 11

**[How To Reproduce]**
1. Using custom font (like NotoSans from google fonts). 
In this case, I use separate font files of its weights from google fonts `(NotoSans-Bold, NotoSans-Regular, NotoSans-Medium)`
2. apply different styling rules using style props
```                      
                    <Markdown
                      style={{
                        body: {
                          fontFamily: Fonts.NotoSansRegular,
                          fontSize: 15,
                        },
                        strong: {
						  fontFamily: Fonts.NotoSansBold
						}
                    >
                      {article.contents}
                    </Markdown>
```
3. Only body styling applied and other nested component's style ignored and followed by system default.(In my case, just fontWeight were applied by default library's option, fontFamily style were overwritten by system font)
![image](https://user-images.githubusercontent.com/29659112/111245822-94f84d00-8648-11eb-9b69-25f2e31a1aef.png)

4. It has same result when using `rules` prop. I tried even replace global styling option `body` to `text`, but it doesn't work.

**Comment by ohmdob** [comment]
same
my workaround
```
<Markdown
              style={{
                body: { fontFamily: typography.medium, color: '#FAA'}
              }}
              rules={{
                strong: (node) => <Text style={{ fontFamily: typography.bold, color: '#FAA'} as ViewStyle} text={node.children[0].content} />
              }}
              >
            {md}
 </Markdown>
```

**Comment by isonlaxman** [comment]
is this still the way to do this? seems like annoying effort just to get bold/italics working

**Comment by dmitry-blackwave** [comment]
Guys, you can try pass node content instead
`strong: (node: ASTNode, _children: ReactNode, _parent: ASTNode[], _styles: StyleProp<any>) => (
    <Text key={node.key}>{node?.children[0]?.content}</Text.Bold>
  ),`

it works well for me

**Comment by jimmi-joensson** [comment]
I solved the android font rendering issue by ensuring that the `fontWeight` is `undefined`.
I don't know why it gets redefined every time I overwrite a strong style, but I have found that defining `strong: { fontWeight: undefined, ...otherStrongStyles }` directly when passing the styles to `<MarkdownDisplay />` solves my issue with incorrect rendered font.

I tested this on an Android 11.0 emulator.

**This does not work:**
```
const strongStyle = { color: 'black' }

<MarkdownDisplay
  style={{
    heading1: {
      color: white
      fontWeight: undefined,
      fontFamily: 'OpenSans_800ExtraBold_Italic',
      fontSize: theme.font.size.h1,
      lineHeight: getHeadingLineHeight(theme.font.size.h1),
      marginBottom: getHeadingMarginBottom(theme.font.size.h1),
      marginTop: theme.font.size.h1,
      textTransform: 'uppercase',
    },
    strong: strongStyle,
  }}
  {...props}>
  # Welcome to the **future** of **living**
</MarkdownDisplay>
```
![image](https://user-images.githubusercontent.com/15996198/171104817-7ba4ae70-5c9c-4842-826b-c41007fc8371.png)

**This works:**
```
const strongStyle = { color: 'black' }

<MarkdownDisplay
  style={{
    heading1: {
      color: white
      fontWeight: undefined,
      fontFamily: 'OpenSans_800ExtraBold_Italic',
      fontSize: theme.font.size.h1,
      lineHeight: getHeadingLineHeight(theme.font.size.h1),
      marginBottom: getHeadingMarginBottom(theme.font.size.h1),
      marginTop: theme.font.size.h1,
      textTransform: 'uppercase',
    },
    strong: { fontWeight: undefined, ...strongStyle },
  }}
  {...props}>
  # Welcome to the **future** of **living**
</MarkdownDisplay>
```
![image](https://user-images.githubusercontent.com/15996198/171104928-cc008698-a1f8-4b36-8d62-99f7e3cb100c.png)
