### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by ospfranco** [iamacup/react-native-markdown-display#139]
Hi! First of all thank you a lot for the awesome plugin! it works wonderfully for most use cases, there is one small hiccup which also wasn't addressed in the original repo, which is syntax highlighting, is there any plan to get that working any time soon?

**Comment by PeterVuyk** [comment]
+1

this would be very helpful

**Comment by isaachinman** [comment]
@iamacup Why was this issue closed? Is there any recommended way to achieve syntax highlighting in code fences?

**Comment by ospfranco** [comment]
Code syntax highlighting is actually not part of markdown and requires something like tree-sitter which would be complex to integrate. I understand why this was closed. You probably want to use a different library for this to keep this package simple.

**Comment by isaachinman** [comment]
Yep, I wasn't expecting it to be included out of the box, but closing an issue without any comment isn't very helpful.
