### ISSUE TITLE
How to use this library with an imported .md file rather than a string literal?

### ISSUE THREAD

**Issue by alexbfree** [iamacup/react-native-markdown-display#142]
Hi, do you or any users of this library have some example code on how to use this library in React Native with an imported local (or indeed, remote) .md file? Thank you.

**Comment by jforaker** [comment]
I did this https://stackoverflow.com/questions/52571450/react-native-expo-load-markdown-files/71679347#71679347 and it works perfectly (in a non-expo app, contrary to the original post)
