### ISSUE TITLE
Missing Text at Android Device

### ISSUE THREAD

**Issue by ardheacp** [iamacup/react-native-markdown-display#143]
Hi, I've a problem with missing text at different device, as example:

Device 1 (there is a missing word at the end of point 2):
![image](https://user-images.githubusercontent.com/22714464/121130036-04509800-c858-11eb-839f-8a70b99edb07.png)

Device 2 (how it should be):
![image](https://user-images.githubusercontent.com/22714464/121130207-47127000-c858-11eb-864e-827739055773.png)

As far what I did is customize `body` style with:
```
    body: {
      fontFamily: 'Inter-Regular',
      fontSize: scaleFont(15),
      lineHeight: 21,
      letterSpacing: 0.05,
      color: Colors.greyDark
    }
```

does anyone have same problem or any idea what i did wrong? thankyou!

**Comment by davidch-lqc** [comment]
I'm facing the same issue, when playing with the line heights, line wrap breaks.. reproducible for iOS as well
