### ISSUE TITLE
list items height is not constant

### ISSUE THREAD

**Issue by mynameisguy** [iamacup/react-native-markdown-display#146]
version: 7.0.0-alpha.2
When putting only the character `_` inside the list, it's shown at the top of the line instead of the bottom:

![Screen Shot 2021-06-28 at 18 50 08](https://user-images.githubusercontent.com/605165/123666968-5c206480-d842-11eb-8da7-3ea75adeae9e.png)

It wasn't the behavior in version 6.1.6 and I'm assuming it's related to #104

**Comment by abirchall** [comment]
Interesting. Possibly due to the line heights that were removed.
