### ISSUE TITLE
Accessibility Support

### ISSUE THREAD

**Issue by lfaz** [iamacup/react-native-markdown-display#152]
It seems like the read speaker reads the whole content as one element (text) even when there is link inside, would it be possible to notify the user about the link and separate text from link as different selectable elements for people who use read speaker?

Basically I want to add focus (accessible={true}) for link elements inside the markdown tag, But there is no way to do it.

Currently for user with vision disabilities is not very informative what the content contains!

**Comment by alanlima-fr** [comment]
Up on that, is there a way to handle accessibility ?
