### ISSUE TITLE
Implicit padding on text

### ISSUE THREAD

**Issue by trajano** [iamacup/react-native-markdown-display#155]
There seems to be an implicit padding on text.  Is there a way of removing it without affecting the semantics of a paragraph?

```
    <VStack space="4">
      <Box borderWidth="1">
        <DefaultMarkdown>asdf</DefaultMarkdown>
      </Box>
      <Box borderWidth="1">
        <Text>asdf</Text>
      </Box>
    </VStack>
```
![image](https://user-images.githubusercontent.com/110627/136125072-63290549-199c-4575-878e-672296be5d66.png)

**Comment by lvwrence** [comment]
@trajano not sure if you figured it out already, but you need to override marginTop and marginBottom in paragraph here: https://github.com/iamacup/react-native-markdown-display/blob/master/src/lib/styles.js#L174

**Comment by NickWhiu** [comment]
May as well close issue, Ivwrence's suggestion works & OP liked it above.

**Comment by OlegBezr** [comment]
The suggestion will also break proper markdown spacing between paragraphs. Is there a way to only disable this top and bottom padding around the whole markdown text?
