### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by danilobuerger** [iamacup/react-native-markdown-display#158]
Hi @iamacup, are you still maintaining this library? It seems like progress has stalled after v7 alpha last year.

**Comment by dpnick** [comment]
Really interested to know that too

**Comment by abirchall** [comment]
Let me know if you're looking for more maintainers. I'm happy to help.

**Comment by CoenWarmer** [comment]
Would be great if a non alpha version could be released, at least :)

**Comment by araujobarret** [comment]
I guess someone else will fork this repo and maintain it for a while there 😂 
`react-native-markdown-display-here-we-go`

No joke part, I'm willing to help if needed but we need a position from the current maintainer

**Comment by iamacup** [comment]
@abirchall @araujobarret, let's have a chat, can you add me on Discord? IaMaCuP#1041

**Comment by dpnick** [comment]
@iamacup I could also help if needed

**Comment by iamacup** [comment]
Feel free to add me @dpnick

**Comment by damau** [comment]
Hey all.  Please let us know the verdict, if the repo will move etc.  Also grateful to the work you have already done iamacup and for those of you to offer to pick it up!  If you do make a verdict I am happy to do a write up (say on the README or something) on what you've decided so that future users know where to go/what to do etc.

**Comment by danilobuerger** [comment]
@iamacup any update on this?

**Comment by caseycoding** [comment]
I'll tag some more people in for visibility: @abirchall, @araujobarret, and @dpnick.

**Comment by vladp** [comment]
adding folks that created a pull request, or asked for maintenance status

 @trajano
 @CodingByJerez
  @inderdhir
  @sdossic

According to the github profile, the author of the repo is no longer active on Git, so we can assume that this repo is no longer maintained.
It needs a fork.
If others have most up-to-date fork that they are willing to share, please post here so that we can at least get by when updating the rest of the libraries (react-native, react, expo, etc)

**Comment by ghost** [comment]
[I've forked it](https://github.com/flowchase/react-native-markdown-display) and republished it under my employer's name because we really needed to incorporate a couple of PRs from others. But TBH I'm not actively maintaining it, it just works for us for now, until we find a better solution.

**Comment by inderdhir** [comment]
Same for me, not actively maintaining at the moment.

**Comment by araujobarret** [comment]
I did some patch locally to support new elements, worked great but didn't publish as a fork

**Comment by damau** [comment]
Hey,

Same.  One contrib.

Is there anyway to create a repo so we we can add a few of us as
collaborators/admin to that repo.  Or for github is it paid only accounts
that would allow that?

I find often the issue with Npm packs is singular responsibilty owners.
Which is a huge burden on them and makes for a ton of forks/patch versions
released on npm.

Ta
Ad

**Comment by vladp** [comment]
@damau  With regards to:  
>" Is there anyway to create a repo so we we can add a few of us as
collaborators/admin to that repo.  Or for github is it paid only accounts
that would allow that? "

Github [docs say](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository): "If you're using GitHub Free, you can add unlimited collaborators on public and private repositories. "

**Comment by RonRadtke** [comment]
Anyone interested in actively continuing on the library?
Otherwise I would fork it and republish. But would be great to have some co-maintainers.
@caseycoding @araujobarret @damau

**Comment by miallo** [comment]
@RonRadtke 
> Anyone interested in actively continuing on the library? Otherwise I would fork it and republish. But would be great to have some co-maintainers.

We in our company already have an internal fork with a few of the most important fixes for us, but we would like to upstream them and take part in the maintenance as well. So you can count @orangecms and me in :)

**Comment by RonRadtke** [comment]
@miallo Then I'll create a repo and invite you both as maintenances so we can republish the lib.
We just need to see that we can integrate you changes too since I made some adjustments for myself already. But don't think that will be a too big problem.

Would that be ok for you?

**Comment by orangecms** [comment]
> @miallo Then I'll create a repo and invite you both as maintenances so we can republish the lib. We just need to see that we can integrate you changes too since I made some adjustments for myself already. But don't think that will be a too big problem.
> 
> Would that be ok for you?

Yup, works for us. :)

If you like, we can also have a chat at some point. We can offer a Jitsi session etc., might help with quicker coordonation. Or a hackathon, since we're just on the other side of the country. ^^

Thank you so much!

**Comment by RonRadtke** [comment]
Sounds great! 
Nice, didn't check your profile yet  :)
Just send me an email to dev@ikascripts.de an we can agree on something. A chat would be useful for sure.

**Comment by RonRadtke** [comment]
Hi,
we teamed up (@orangecms @miallo and me) to keep this project alive.
We forked it: https://www.npmjs.com/package/@ronradtke/react-native-markdown-display
We started integrating fixes and some additional functionality targeting accessibility, theming, and general issues like combability to new versions of RCT.
