### ISSUE TITLE
Could you make it work with react 17.0?

### ISSUE THREAD

**Issue by baochungit** [iamacup/react-native-markdown-display#159]
I'm using react native with react version 17.0.1 and it seems not working well together.
Could you spend a little time to make it work?
Thanks a lot!

**Comment by andreasciamanna** [comment]
I second this request.

Thanks.

**Comment by SergeWilfried** [comment]
Hi, me too. Thanks

**Comment by Pedro-Goncal** [comment]
Yes please and thank you

**Comment by nicobermudez** [comment]
Bump

**Comment by SDuBey001** [comment]
is this abandoned? If so we'll need to find a new solution. We require minimum React 17 and this is tossing errors because it is looking for 16.2!

**Comment by subhranshudas** [comment]
I have an EXPO created app with below -
```
{
  "name": "mobile",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~45.0.0",
    "expo-status-bar": "~1.3.0",
    "punycode": "^2.1.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-markdown-display": "^7.0.0-alpha.2",
    "react-native-web": "0.17.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
```

which seems to be working with   "react": "**17.0.2**",

Which scenarios are you guys getting errors?

**Comment by Palhanor** [comment]
I was also facing some problems with the project reacted using Expo and React Native 17.0.2.

But then, @subhranshudas shared his package.json configuration, and i`ve noticed that the error my Expo was showing to me said something like "punycode could not be found within the project".

So I connected the dots and then I just installed the [punycode](https://www.npmjs.com/package/punycode), and just like that, out of the blue, the React Native Markdown Display worked in the project.

So right now I believe that somehow the punycode package is not getting installed as a dependency of this library, and thats probably one of the reasons of the current problem.

**Comment by nourspace** [comment]
For those wondering how to get this to work with Expo in 2023 using this working fork https://github.com/flowchase/react-native-markdown-display.

```sh
npm install git+https://github.com/flowchase/react-native-markdown-display
expo install punycode
```

You have to use this for importing Markdown
```js
import Markdown from '@flowchase/react-native-markdown-display'
```
