### ISSUE TITLE
List items (ordered + unordered) are not rendered on same line

### ISSUE THREAD

**Issue by hassiebp** [iamacup/react-native-markdown-display#161]
Hey all,

happy new year!

Unfortunately markdown with ordered or unordered lists are not rendered on the same line / aligned correctly. Any hints on how to fix this behavior? Snack with minimal repro: https://snack.expo.dev/@hassieb/react-native-markdown-display-ordered-list  

![rendered lists](https://user-images.githubusercontent.com/68423100/147878216-559c75a4-8184-4363-a88e-7736a1638ca1.png)

**Comment by hannojg** [comment]
is this on android? You might want to set `includeFontPadding: false` in the styles of the markdown component and try that

**Comment by hassiebp** [comment]
Thanks for the suggestion @hannojg ! Unfortunately, this issue exist cross-platform (see link to Snack above) and the includeFontPadding option does not fix the issue at least from what I've tried

**Comment by difasulthon** [comment]
I have the same issue, how to fix it?

**Comment by malikbanuaji** [comment]
i think adding `width` to ordered_list_icon or unordered_list_icon fix it, it was not aligned correctly because they have different font width.
```
markdown: {
  ordered_list_icon: {
    width: 14 // or your value
  }
}
```

**Comment by difasulthon** [comment]
> i think adding `width` to ordered_list_icon or unordered_list_icon fix it, it was not aligned correctly because they have different font width.
> 
> ```
> markdown: {
>   ordered_list_icon: {
>     width: 14 // or your value
>   }
> }
> ```

It is solved for me. Thank you for the suggestion
