### ISSUE TITLE
can't apply styles to a bullet_list

### ISSUE THREAD

**Issue by y-maslouskaya** [iamacup/react-native-markdown-display#162]
I am trying to add styles for bullet_list like these:
`  bullet_list: {
     marginTop: 16,
     marginBottom: 50,
     lineHeight: 22,
  },`

But, unfortunately, nothing is changing. When I do the same for ordered_list, it works just fine.

**Comment by onepointconsulting** [comment]
Have you tried something like this:

```
    bullet_list_icon: {
        marginLeft: 10,
        marginRight: 10
    },
    // @pseudo class, does not have a unique render rule
    bullet_list_content: {
        fontSize: 14,
        flex: 1,
    }

```

**Comment by y-maslouskaya** [comment]
@onepointconsulting Thank you. It helped.
