### ISSUE TITLE
Incremental rendering for large markdowns

### ISSUE THREAD

**Issue by pke** [iamacup/react-native-markdown-display#164]
Would it somehow be possible to render large markdown documents incrementally?
Like a virtual list view but with markdown blocks in it?

**Comment by anisimov74** [comment]
@pke i did using `stringToTokens` and `tokensToAST` together and regulating how many nodes you want to render.

**Comment by pke** [comment]
Could you maybe please provide a code snippet here. Maybe we could add such functionality into the library.

**Comment by anisimov74** [comment]
@pke sure. You can find it [here](https://github.com/JetBrains/youtrack-mobile/blob/79f67b72069fc8ccdf73e901b3307ca27f8b99f1/src/components/wiki/markdown-view-chunks.js#L60).
This is not a perfect solution, but it fixes performance problems for the most cases.
And you can also try to render AST in a FlatList to get virtualizing.
