### ISSUE TITLE
react-native-markdown-display not recognizing <u> tag

### ISSUE THREAD

**Issue by SapnaBhadauria** [iamacup/react-native-markdown-display#165]
Change of terms is inside "u" "/u" but markdown is not displaying underline and Change of terms is inside a paragraph. Please suggest.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/102813469/161282788-021ee041-55a6-4acb-a710-5bab1673b895.png">

**Comment by ivankdev** [comment]
there is no underline support, you can try to find custom markdownit plugin for this library (see how to connect plugin in description) or use hack with empty link if applicable for you like `[Change of Terms]() `

**Comment by SapnaBhadauria** [comment]
@aviemore , thanks for the suggestion.
