### ISSUE TITLE
Markdown text flickers on every state update, using the normal <Text> from react native does not

### ISSUE THREAD

**Issue by jimdog1001** [iamacup/react-native-markdown-display#169]
i have markdown with some text style applied. Every state update the text flickers. But if i use the React native Text field instead of the Markdown component to render the text, this issue does not occur

**Comment by jimdog1001** [comment]
also this only seems to be happening on android

**Comment by TahseenSust** [comment]
Does anyone found any solution for this issue? I am also facing this in iOS
