### ISSUE TITLE
Select and copy text by using rules

### ISSUE THREAD

**Issue by y-maslouskaya** [iamacup/react-native-markdown-display#173]
I am trying to allow to select and paste text. I found a related question under the issue #126, so I decided to try rules to change component to <Text></Text> and apply selectable={true}. But for some reason the text disappeared (only numbers were left) in my component after I had added rules. Did I write rules incorrectly? Thank you in advance!

` ordered_list: (node, children, parent, styles) => (
      <Text key={node.key}
        style={styles.ordered_list} selectable={true}>
        {children}
      </Text>
    ),
`
<img width="366" alt="Screen Shot 2022-06-21 at 6 38 12 PM" src="https://user-images.githubusercontent.com/59900627/174913793-769ec87f-1d56-4bfb-9b2e-40886d8804b5.png">

**Comment by luco** [comment]
Same here

**Comment by esalaza** [comment]
See my [comment](https://github.com/iamacup/react-native-markdown-display/issues/126#issuecomment-1619644124) in #126 for an alternative.

**Comment by Polombo98** [comment]
This is the original rule for text:
`text: (node, children, parent, styles, inheritedStyles = {}) => (
    <Text key={node.key} style={[inheritedStyles, styles.text]}>
      {node.content}
    </Text>
  ),`
  
  As you can see, it uses node.content
  
  Please use it to get the text

**Comment by isaachinman** [comment]
Anyone have an actual example of how to implement this?

```tsx
import Markdown from 'react-native-markdown-display'

<Markdown style={{ body: { userSelect: 'auto' } }} />
```

This sort of straightforward/basic approach is not working.

**Comment by mengheangrat** [comment]
`const rules = {
    textgroup: (node, children, parent, myStyles, inheritedStyles = {}) => {
      return (
        <Text
          key={node.key}
          style={[inheritedStyles, styles.textMarkdown]}
          selectable={true}
          selectionColor={CONSTANT.SECONDARY_LIGHT_GREY}>
          {children}
        </Text>
      );
    },
  };`
  
  Apply this rule you will be able to select all text.
