### ISSUE TITLE
React 17 support?

### ISSUE THREAD

**Issue by sdossick** [iamacup/react-native-markdown-display#174]
Hi, any reason not to take one of the pull requests that have been submitted to allow the library to work with React 17?

**Comment by pwfcurry** [comment]
https://github.com/iamacup/react-native-markdown-display/issues/158

**Comment by RonRadtke** [comment]
You can switch over to: https://www.npmjs.com/package/@ronradtke/react-native-markdown-display
We created a fork and keep maintaining it.
