### ISSUE TITLE
children not assignable in Markdown component

### ISSUE THREAD

**Issue by bitboxer** [iamacup/react-native-markdown-display#176]
I am getting this error when using typescript:

```javascript
Type '{ children: string; style: { body: { fontSize: number; lineHeight: number; color: string; fontFamily: string; }; heading1: { fontSize: number; lineHeight: number; fontWeight: "bold"; }; heading2: { fontSize: number; lineHeight: number; fontWeight: "bold"; }; ... 4 more ...; bullet_list_icon: { ...; } | { ...; }; }; ...' is not assignable to type 'IntrinsicAttributes & MarkdownProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & MarkdownProps'.
```

Adding

```js
children?: ReactNode
```

To the 

```js
export interface MarkdownProps {
```

Fixes it for me.

**Comment by ipoogleduck** [comment]
I'm getting the same issue

**Comment by ovezovv** [comment]
Same here also as well as @bitboxer defined above adding:

```ts
  children?: ReactNode;
```

to the `node_modules/react-native-markdown-display/src/index.d.ts` fixed type error, working variant is below:

```ts
  export interface MarkdownProps {
    rules?: RenderRules;
    children?: ReactNode;
    style?: StyleSheet.NamedStyles<any>;
    renderer?: AstRenderer;
    markdownit?: MarkdownIt;
    mergeStyle?: boolean;
    debugPrintTree?: boolean;
    onLinkPress?: (url: string) => boolean;
  }
```

Please, consider this I am using version **7.0.0-alpha.2**

**Comment by alihussnain-git** [comment]
any chances if this issue can be fixed?

**Comment by bitboxer** [comment]
@alihussnain-git you can use [patch-package](https://www.npmjs.com/package/patch-package) to fix it temporary for yourself.

**Comment by alihussnain-git** [comment]
> @alihussnain-git you can use [patch-package](https://www.npmjs.com/package/patch-package) to fix it temporary for yourself.

Or simply use ts-ignore 😁

**Comment by flodev** [comment]
I've extended the types
Somewhere in you code add a `Markdown.d.ts`

insert 

```ts
import { ComponentType, ReactNode } from 'react';
import { MarkdownProps } from 'react-native-markdown-display';

declare module 'react-native-markdown-display' {
  export const ExtendedMarkdown: ComponentType<
    {
      children: ReactNode;
    } & MarkdownProps
  >;
  export = ExtendedMarkdown;
}
```

make sure the type file is in the folders mentioned in `"typeRoots": ["./node_modules/@types", "./src/types"]` in your tsconfig.json

**Comment by mguerrero-exe** [comment]
> I've extended the types Somewhere in you code add a `Markdown.d.ts`
> 
> insert
> 
> ```ts
> import { ComponentType, ReactNode } from 'react';
> import { MarkdownProps } from 'react-native-markdown-display';
> 
> declare module 'react-native-markdown-display' {
>   export const ExtendedMarkdown: ComponentType<
>     {
>       children: ReactNode;
>     } & MarkdownProps
>   >;
>   export = ExtendedMarkdown;
> }
> ```
> 
> make sure the type file is in the folders mentioned in `"typeRoots": ["./node_modules/@types", "./src/types"]` in your tsconfig.json

This worked for me :D
