### ISSUE TITLE
Custom tags support?? like markdown-to-jsx

### ISSUE THREAD

**Issue by subhranshudas** [iamacup/react-native-markdown-display#177]
Hello All,
I am trying to support the following -
1. Plain Markdown
2. JSX styled tags (e.g. `<MyCustomTag color="blue">Hello There</MyCustomTag>`)
3. Mix of above 2.

For the **React web** part i am able to implement the above 3 with the below package
https://www.npmjs.com/package/markdown-to-jsx

Now i wanted the same support for **React-Native** apps.

My query-
I have been able to support (1) with this package, but need a way to support (2) & (3) ??

Any pointers??

Thanks!!

**Comment by pavan168** [comment]
Did you manage to solve this?
