### ISSUE TITLE
children typescript erorr

### ISSUE THREAD

**Issue by ovezovv** [iamacup/react-native-markdown-display#181]
Adding this:

```ts
  children?: ReactNode;
```

to the `node_modules/react-native-markdown-display/src/index.d.ts` fixed type error, working variant is below:

```ts
  export interface MarkdownProps {
    rules?: RenderRules;
    children?: ReactNode;
    style?: StyleSheet.NamedStyles<any>;
    renderer?: AstRenderer;
    markdownit?: MarkdownIt;
    mergeStyle?: boolean;
    debugPrintTree?: boolean;
    onLinkPress?: (url: string) => boolean;
  }
```

Please, consider this I am using version **7.0.0-alpha.2**

**Comment by miallo** [comment]
Unfortunately this project is no longer maintained. The last alpha release you mentioned is two years old and there was no further commit in this repo...

**Comment by pwfcurry** [comment]
See my answer here https://github.com/oblador/react-native-collapsible/issues/450#issuecomment-1328800327 for a temporary workaround.

See also https://github.com/iamacup/react-native-markdown-display/issues/158

**Comment by a8c71** [comment]
thank you @pwfcurry , below is the file I added and its now working

```typescript
// md-children-fix.d.ts

import React from 'react';

declare module 'react-native-markdown-display' {
  // https://www.typescriptlang.org/docs/handbook/declaration-merging.html#merging-interfaces
  interface MarkdownProps {
    children?: React.ReactNode;
  }
}
```
