### ISSUE TITLE
Peer dependency requirement of newer react versions

### ISSUE THREAD

**Issue by yittoo** [iamacup/react-native-markdown-display#184]
Issue Context:
With newer versions of react, we are receiving the warning of 
`npm WARN react-native-markdown-display@7.0.0-alpha.2 requires a peer of react@^16.2.0 but none is installed. You must install peer dependencies yourself.`

Can this be revised for newer versions of react-native?

**Comment by pwfcurry** [comment]
https://github.com/iamacup/react-native-markdown-display/issues/158

**Comment by RonRadtke** [comment]
You can switch over to:  https://www.npmjs.com/package/@ronradtke/react-native-markdown-display
We created a fork and keep maintaining it.

**Comment by WelshDev** [comment]
@RonRadtke I've tried your fork, I'm getting "Unable to resolve module react-native-markdown-display" when trying to import it.

Installed using...
`npm i @ronradtke/react-native-markdown-display`

Imported like this...
`import Markdown from "react-native-markdown-display"`

From package.json...
``` 
"react": "18.1.0",
"react-native": "0.70.6",
"@ronradtke/react-native-markdown-display": "^7.0.0-alpha.2"
```

Thanks!

**Comment by RonRadtke** [comment]
Try to change the import to ``` import Markdown from '@ronradtke/react-native-markdown-display';```
