### ISSUE TITLE
Error when using code block

### ISSUE THREAD

**Issue by Wepa121** [iamacup/react-native-markdown-display#188]
fontFamily "Courier" is not a system font and has not been loaded through Font.loadAsync.

**Comment by sturmenta** [comment]
The solution is use `expo-google-fonts` and load in the start of the app

1) `npx expo install @expo-google-fonts/courier-prime expo-font`
2) use [expo-app-loading](https://github.com/expo/google-fonts#in-your-app) or [expo-splash-screen](https://docs.expo.dev/develop/user-interface/fonts/#minimal-example) for show loading while the font is loaded
  
I preferred to use the splash screen for show loading.

> this code is an example using expo-router, if you are not using expo-router, you should do something very similar but in App.js/tsx

```js
import { useCallback } from 'react';
import { Slot } from 'expo-router';
import * as SplashScreen from 'expo-splash-screen';
import { useFonts, CourierPrime_400Regular } from '@expo-google-fonts/courier-prime';

SplashScreen.preventAutoHideAsync();

export default function RootLayout() {
  const [fontsLoaded] = useFonts({ Courier: CourierPrime_400Regular });

  const onLayoutRootView = useCallback(async () => {
    if (fontsLoaded) await SplashScreen.hideAsync();
  }, [fontsLoaded]);

  if (!fontsLoaded) return null;

  return (
      <Slot screenOptions={{ onLayoutRootView }} />
  );
}
```
