### ISSUE TITLE
No support for <u> tag & Link click does not work &  & Can't pass both style and rules at the same time

### ISSUE THREAD

**Issue by ebasic** [iamacup/react-native-markdown-display#193]
Still no support for `<u>` tags. Looking forward for some suggestions how to add some custom solutions.

Tried to pass `styles` and `rules` at the same time (used default styles and rules provided on official documentation) but app crashed and TS raised an error too. Styles alone work perfectly and I was able to change stylings on desired elements, but now I wanted to customize rule for `link` because click on it didn't work although it rendered link correctly (underlined and colored as I specified in styles).

Screenshot from IDE:

<img width="972" alt="Screenshot 2023-05-13 at 01 54 34" src="https://github.com/iamacup/react-native-markdown-display/assets/11341609/19c129b9-56a6-4721-8e12-b8af1e0ff05c">

Screenshot from app crashed:
![image_123986672](https://github.com/iamacup/react-native-markdown-display/assets/11341609/448389ee-092a-4d0f-9f41-ef22b8660ca6)

**Comment by ebasic** [comment]
@iamacup No support for underline, bold and italic for some reason, React 18. It just renders html tags as normal text.

**Comment by sebastianjung** [comment]
@ebasic 
You might want to check that you are not overwriting default body styles with something like
`fontFamily: "Overpass_400Regular"`

Had this problem with bold and italic not being applied. <u> is still not parsed correctly though...

**Comment by darishodzic** [comment]
Solution for underline:
`const contentWithUnderline = content?.replaceAll('<u>', '[')?.replaceAll('</u>', ']()')`
