### ISSUE TITLE
Type for MarkdownStatic's component props is missing `children`

### ISSUE THREAD

**Issue by jefflewis** [iamacup/react-native-markdown-display#196]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-markdown-display@7.0.0-alpha.2` for the project I'm working on.

The types for this project do not currently have `Children`. 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-markdown-display/src/index.d.ts b/node_modules/react-native-markdown-display/src/index.d.ts
index f0daf4a..9b11a0c 100644
--- a/node_modules/react-native-markdown-display/src/index.d.ts
+++ b/node_modules/react-native-markdown-display/src/index.d.ts
@@ -1,7 +1,7 @@
 // tslint:disable:max-classes-per-file
 import MarkdownIt from 'markdown-it';
 import Token from 'markdown-it/lib/token';
-import {ComponentType, ReactNode} from 'react';
+import {ComponentType, PropsWithChildren , ReactNode} from 'react';
 import {StyleSheet, View} from 'react-native';
 
 export function getUniqueID(): string;
@@ -91,7 +91,7 @@ export interface MarkdownProps {
   onLinkPress?: (url: string) => boolean;
 }
 
-type MarkdownStatic = ComponentType<MarkdownProps>;
+type MarkdownStatic = ComponentType<PropsWithChildren<MarkdownProps>>;
 export const Markdown: MarkdownStatic;
 export type Markdown = MarkdownStatic;
 export {MarkdownIt};
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by dendenmuniz** [comment]
Sorry, but how can I use this fix?

**Comment by Balake** [comment]
@dendenmuniz  If you don't want to wait for a release, you can do this:

```
import React, { ComponentType, PropsWithChildren } from 'react';
import _Markdown, { MarkdownProps } from 'react-native-markdown-display';

type MarkdownWithChildrenT = ComponentType<PropsWithChildren<MarkdownProps>>;
const Markdown = _Markdown as MarkdownWithChildrenT;

export const SomeComponent: React.FunctionComponent = () => {
    const md = '';
    return (
        <Markdown>{md}</Markdown>
    );
};
```

**Comment by LeonAvancini** [comment]
@dendenmuniz You should go directly to node modules where you have the library installed, then change the necessary code, in this case are only two lines:

`import {ComponentType, PropsWithChildren , ReactNode} from 'react';`
`type MarkdownStatic = ComponentType<PropsWithChildren<MarkdownProps>>;`

After you did the necessary changes play with the code and check if everything is working as you expected.

If everything is working well you should create the patch, to do that I recommend you read the documentation, it's just execute a command `npx patch-package <package_name>` 
but before that you need to install [patch-package library](https://www.npmjs.com/package/patch-package) and configure some scripts on your `package.json` and that should be all.
I hope help with this comment.

**Comment by MilanBarande** [comment]
I created [a pull request ](https://github.com/iamacup/react-native-markdown-display/pull/198)for this issue @iamacup
