### ISSUE TITLE
In the flex row layout, the list will be truncated

### ISSUE THREAD

**Issue by xuergo** [iamacup/react-native-markdown-display#197]
This may not be a bug, but it troubles me. I share it with others in the hope of being helpful

``` 
<View className='flex-row'>
  <View className='w-[10px] h-[10px] bg-black'></View>
  <Markdown>
    {` 1. hi`}
  </Markdown>
</View>
```
## Bad
<img width="514" alt="image" src="https://github.com/iamacup/react-native-markdown-display/assets/46159623/ec17767e-8913-4c2e-b4d5-579de91c7c1b">

```
 <View className='flex-row'>
          <View className='w-[10px] h-[10px] bg-black'></View>
          <Markdown style={{ ordered_list_content: { flex: 0 } }} >
            {` 1. hi`}
          </Markdown>
        </View>
```
## Good
<img width="565" alt="image" src="https://github.com/iamacup/react-native-markdown-display/assets/46159623/fb81bf08-f367-4a6b-b20f-d98aad509ead">

**Comment by rcidt** [comment]
So.... what was the solution? @xuergo

**Comment by xuergo** [comment]
> So.... what was the solution? @xuergo 

```

<Markdown style={{ ordered_list_content: { flex: 0 } }} >
            {` 1. hi`}
          </Markdown>

```
