### ISSUE TITLE
Table alignment ignored

### ISSUE THREAD

**Issue by iamacup** [iamacup/react-native-markdown-display#42]
![android-8](https://user-images.githubusercontent.com/12894620/70247797-e3464d00-1771-11ea-8768-6956dec5f363.png)
![ios-8](https://user-images.githubusercontent.com/12894620/70247802-e6413d80-1771-11ea-8d84-4948addfccf2.png)

**Comment by iamacup** [comment]
This is a pain and is caused because of the wrapping of the textgroup rule on the underlying text. 

The textgroup rule is added manually by this library because it is needed for wrapping text with text to allow multi line stuff - example below:

![image](https://user-images.githubusercontent.com/12894620/70252721-cd3c8a80-1779-11ea-864e-16762829af51.png)

```
{/* this is how it is today - displayed correctly - View is a paragraph, Text is textgroup and child Text's are text*/}
<View style={{
    flexWrap: 'wrap',
    flexDirection: 'row',
    width: '100%'}}>
  <Text>
    <Text>hey there</Text>
    <Text style={{color: 'red'}}> some in line code hilight or something that is really long =wooooo </Text>
    <Text>the final bit of text</Text>
  </Text>
</View>

<View style={{marginTop: 30}}></View>

{/* this is how it would be - with no text group - displayed correctly - View is a paragraph, child Text's are text*/}
<View style={{
    flexWrap: 'wrap',
    flexDirection: 'row',
    width: '100%'}}>
  <Text>hey there</Text>
  <Text style={{color: 'red'}}> some in line code </Text>
  <Text>the final bit of text</Text>
</View>

<View style={{marginTop: 30}}></View>

{/* this is how it would be - with no text group - showing the problem without text group - View is a paragraph, child Text's are text*/}
<View style={{
    flexWrap: 'wrap',
    flexDirection: 'row',
    width: '100%'}}>
  <Text>hey there</Text>
  <Text style={{color: 'red'}}> some in line code hilight or something that is really long =wooooo </Text>
  <Text>the final bit of text</Text>
</View>
```

The problem is that the text group `<Text>` element wrapping the actual display `<Text>` item prevents the actual display item from applying the style correctly on android. Not sure exactly what to do but ideally it would be great to remove the textgroup item all together....

**Comment by santimone** [comment]
i dont understand why this issue is completed, none of the issues linked is a clear fix to the problem
