### ISSUE TITLE
Can't give a code_block custom style

### ISSUE THREAD

**Issue by keanfreeman** [iamacup/react-native-markdown-display#51]
I'm able to override the code_block with the following code.

```javascript
rules = {
    code_block: (node, children, parent, style) => {
        return <Text>I am a code_block</Text>;
    }
}

<Markdown rules={rules}>
    {myString}
</Markdown>
```

However, I can't give code_block a custom style (for example, a different text color) with similar code, even though I can modify the style of other components.

```javascript
style = {
    root: { color: "red" }, // works on its own
    code_block: { color: "red" } // doesn't work on its own
}

<Markdown style={style}>
    {myString}
</Markdown>
```

Any thoughts?
I'm doing this because I'm setting the "root" text color to be white, but the background color of the code_block is close to white, so it's impossible to read. I'd like to either change the text color or the background color of the code_block, but I can't seem to do it.

**Comment by iamacup** [comment]
This is because of bad / confusing naming of the rules and the styles

take a look at the readme and you will see that the style for code blocks is not the same name as the rules:

```jsx
const copy = `
# Boom title

Some text

\`\`\`
  Code block
\`\`\`

\`inline code thing\`
`;

const styles = StyleSheet.create({
    root: { color: "red" },
    codeBlock: { color: "blue" }
});
```

![image](https://user-images.githubusercontent.com/12894620/75032920-99801f80-54a1-11ea-828c-4dfbe7a98a36.png)


I would like to clean this up, but because of backwards compat with `react-native-markdown-renderer` its really tough.

**Comment by keanfreeman** [comment]
Thanks, I appreciate it.

**Comment by iamacup** [comment]
just to let you know @keanfreeman i am sick of the difference between the styles and render rules so 6.0.0 just changes them all to match

| Render Rule | Style(s) |
| ------ | ----------- |
| `body` | `body` | 
| `heading1` | `heading1` |
| `heading2` | `heading2` |
| `heading3` | `heading3` |
| `heading4` | `heading4` |
| `heading5` | `heading5` |
| `heading6` | `heading6` | 
| `hr` | `hr` | 
| `strong` | `strong` | 
| `em` | `em` | 
| `s` | `s` | 
| `blockquote` | `blockquote` | 
| `bullet_list` | `bullet_list` | 
| `ordered_list` | `ordered_list` | 
| `list_item` | `list_item` - This is a special case that contains a set of pseudo classes that don't align to the render rule: `ordered_list_icon`, `ordered_list_content`, `bullet_list_icon`, `bullet_list_content` | 
| `code_inline` | `code_inline` | 
| `code_block` | `code_block` | 
| `fence` | `fence` | 
| `table` | `table` | 
| `thead` | `thead` | 
| `tbody` | `tbody` | 
| `th` | `th` | 
| `tr` | `tr` | 
| `td` | `td` | 
| `link` | `link` | 
| `blocklink` | `blocklink` | 
| `image` | `image` | 
| `text` | `text` | 
| `textgroup` | `textgroup` | 
| `paragraph` | `paragraph` | 
| `hardbreak` | `hardbreak` | 
| `softbreak` | `softbreak` | 
| `pre` | `pre` | 
| `inline` | `inline` | 
| `span` | `span` |

**Comment by keanfreeman** [comment]
Seems like a good change!

**Comment by JosuGZ** [comment]
Hi, I can get `code_inline` working, but not `code_block` (nor `codeBlock`):

Source:
![image](https://user-images.githubusercontent.com/25986871/111921175-70123880-8a93-11eb-87aa-ab97b7e6c874.png)

Result:
![image](https://user-images.githubusercontent.com/25986871/111921188-7c969100-8a93-11eb-8038-2fad9dd7a635.png)


My style sheet:

```
const styles = StyleSheet.create({
  heading1: {
    fontSize: 32,
    // backgroundColor: '#000000',
    color: '#E94B3CFF',
  },
  heading2: {
    fontSize: 24,
    color: '#E94B3CFF',
  },
  heading3: {
    fontSize: 18,
    color: '#E94B3CFF',
  },
  heading4: {
    fontSize: 16,
    color: '#E94B3CFF',
  },
  heading5: {
    fontSize: 13,
    color: '#E94B3CFF',
  },
  heading6: {
    fontSize: 11,
    color: '#E94B3CFF',
  },
  code_inline: {
    color: '#E94B3CFF',
    backgroundColor: '#2D2926FF',
  },
  code_block: {
    color: '#E94B3CFF',
    backgroundColor: '#2D2926FF',
  },
  blockquote: {
    color: '#E94B3CFF',
    backgroundColor: '#2D2926FF',
  },
});
```

**Comment by itsmesaskovic** [comment]
@JosuGZ I got it working using **fence** instead of code_block:

```
 fence: {
    color: '#E94B3CFF',
    backgroundColor: '#2D2926FF',
  },
```

**Comment by JosuGZ** [comment]
> @JosuGZ I got it working using **fence** instead of code_block:
> 
> ```
>  fence: {
>     color: '#E94B3CFF',
>     backgroundColor: '#2D2926FF',
>   },
> ```

Thanks, it works!

Aparently, this:

```

    Code here

```

is not the same than this:

````
```
Code here
```
````
