### ISSUE TITLE
Text renderRule is not accepting textBreakStrategy prop

### ISSUE THREAD

**Issue by abelyeupear** [iamacup/react-native-markdown-display#52]
Since Android 10, `textBreakStrategy="simple"` is necessary for the text not to break in a way that can hide the last word of the text. Apparently, only the prop mentioned above solves this issue.

I tried adding this prop to the `text` renderRule like:
```
text: (node, children, parent, styles) => {
    return <Text key={node.key} textBreakStrategy="simple">{node.content}</Text>;
  },
```
But the prop is not being applied appropriately, or, at least, the text is still breaking. I have two questions:

1. Am I missing something about how this is supposed to work?
2. Is there a way to make sure this `textBreakStrategy="simple"` is applied?

**Comment by jayshah123** [comment]
Yes, It seems even "numberOfLines" prop is not respected right now.

**Comment by abelyeupear** [comment]
So, apparently, the prop does apply to the `textgroup` rule!
I still don't quite understand how the parser/renderer works, and why it would be `textgroup` vs. `text` rule, but it certainly did the trick.
Hope this helps!

**Comment by iamacup** [comment]
A couple of things here - the horrible textgroup / text hierarchy is explained here: https://github.com/iamacup/react-native-markdown-display/issues/42#issuecomment-562199006

Its a pain.... but I don't know another way of doing it.

@jayshah123 as a consequence of having to nest the text elements - this bug: https://github.com/facebook/react-native/issues/22811 is causing the numberOfLines prop to not work

@abelyeupear i am struggling to replicate the underlying issue on an emulator set to API 29 // Android 10 - what specifically is happening? can you provide me a sample / screenshots? :)

**Comment by iamacup** [comment]
Closing because i am not sure what next steps are without some help from @abelyeupear - feel free to reopen

**Comment by abelyeupear** [comment]
Sorry, busy week!
No need to reopen, I think the issue was mainly that it the prop had to go into the `textgroup` rule. I haven't had time to look into the text/textgroup hierarchy, but if that needed to get fixed at some point, it sounds like a completely different issue.

The steps to reproduce are mainly: Android 10 (emulator or not), `<Text>` component and enough text to break the line into a new line by one word only. In Android 10, this word won't show up.
The fix is to use `textBreakStrategy='simple'` in the Text component, in the `textgroup` rule.

**Comment by iamacup** [comment]
I will reopen because it seems that the default textgroup rule should maybe have the breackStrat added as you say,

Will do some more testing over the next couple of days and see!

**Comment by helsonxiao** [comment]
I use this rule as a workaround for `numberOfLines`.

```jsx
const rules: RenderRules = {
  ...YourRules,
  textgroup: node => {
    return (
      <Text
        key={node.key}
        numberOfLines={3}
      >
        {node.children?.[0].content}
      </Text>
    );
  },
};
```
