### ISSUE TITLE
Property 'mergeStyle' does not exist on type 'IntrinsicAttributes & MarkdownProps & { children?: ReactNode; }'.

### ISSUE THREAD

**Issue by aekaisato** [iamacup/react-native-markdown-display#53]
When using the mergeStyle prop using Markdown as in this example,

```
          <Markdown style={stylesMd} mergeStyle={true}>
                  {itemState.content}
          </Markdown>
```
a linting error is displayed claiming that
Property 'mergeStyle' does not exist on type 'IntrinsicAttributes & MarkdownProps & { children?: ReactNode; }'.

The program itself works fine, but it may be helpful to prevent this from showing.
I'm using VSCode.

**Comment by iamacup** [comment]
Hmmmmm, is this to do with the typescript defs do you think?

**Comment by aekaisato** [comment]
I'm actually unsure. Sorry.

**Comment by iamacup** [comment]
can you please test something for me

can you please delete (or move somewhere else) this file - `node_modules/react-native-markdown-display/src/index.d.ts`

and tell me if the error vanishes?

**Comment by aekaisato** [comment]
Yes, it does. Also, by adding `mergeStyle?: boolean;` to MarkdownProps the issue is fixed. I'll submit a pull request.

**Comment by iamacup** [comment]
Super, 6.0.1 released with the fix

Thanks @realToadtoad !
