### ISSUE TITLE
Can't specify link color

### ISSUE THREAD

**Issue by ewal** [iamacup/react-native-markdown-display#55]
I can change all other styles on a link like `textDecorationLine` and `backgroundColor` but the `color` property doesn't do anything.

**Comment by iamacup** [comment]
Can you send all your code?

I imagine you might have a color style on the `text style`?

this works for me:

# Using merge style so the underline is kept

```
const styles = StyleSheet.create({
  link: { color: 'red' }
});


const copy = `
# Title

[My super duper link](http://www.google.com)

`;


const App: () => React$Node = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView
          style={{height: '100%'}}
        >
          
           <Markdown style={styles} mergeStyle={true}>{copy}</Markdown>
          
        </ScrollView>
      </SafeAreaView>
    </>
  );
};
```

OR

# Directly specify the color and underline

```
const styles = StyleSheet.create({
  link: { color: 'red', textDecorationLine: 'underline', }
});


const copy = `
# Title

[My super duper link](http://www.google.com)

`;


const App: () => React$Node = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView
          style={{height: '100%'}}
        >
          
           <Markdown style={styles}>{copy}</Markdown>
          
        </ScrollView>
      </SafeAreaView>
    </>
  );
};
```

![image](https://user-images.githubusercontent.com/12894620/75033924-ee249a00-54a3-11ea-895e-7a600f263c87.png)

**Comment by iamacup** [comment]
Feel free to re-open if this is still an issue after 6.0.1

**Comment by samitha9125** [comment]
@iamacup Seems like this does not work anymore.

**Comment by iamacup** [comment]
please share some more details, react native version, emulator, environment setup, operating system, full code snip etc

its working fine for me.

**Comment by kuriel-trivu** [comment]
Not working. Not able to change **link** color.

```
"react-native-markdown-display": "7.0.0-alpha.2",
"react-native": "https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz",
```

```
node -v
v12.20.0
npm -v
6.14.8
```

**Comment by kuriel-trivu** [comment]
removing

`mergeStyle={true}`

works!

**Comment by yaiMaimak** [comment]
Just Change The Text output bro.

<Markdown style={{
              text: {
                color: "#000000"
              },
            }} mergeStyle={true}>{item.text}</Markdown>

**Comment by sraut1** [comment]
@iamacup thanks for library man, how do I set background color to occupy entire screen width for a link? it doesnt seem to take its parents width.
