### ISSUE TITLE
TypeScript defs are out of date

### ISSUE THREAD

**Issue by iamacup** [iamacup/react-native-markdown-display#56]
Would really love it if someone could help update them from the PropTypes and Readme info :)

**Comment by lukeramsden** [comment]
Only issue I've encountered so far I think is that RenderFunction->parent is currently typed as `ReactNode`, but from a preliminary look at the code it seems that it's actually `ReactNode[]` like children? Hard to tell as this is my first experience with this package. I'll see what issues I run in to using this in my TypeScript project and I'll see if I can get round to a PR.

EDIT: Oh now I think I understand better, `RenderFunction` is actually passed an array of `ASTNode` and not `ReactNode`, I think?

**Comment by iamacup** [comment]
I have pruned out some stuff that was not used as part of 6.1.0, although i don't think it impacts your question here just some stuff in the defs file.

I just looked at the RenderRule->parent property, its actually a really badly labeled thing - it is the parents - 0th most immediate, nth most distant - which are type `ASTNode` yes!

Note that the 'nth' item is special and manually generated (the body type) like this:

```
const root = {type: 'body', key: getUniqueID(), children: nodes};
```
