### ISSUE TITLE
Is it possible to render markdown under <Text> </Text> tag ?

### ISSUE THREAD

**Issue by MuhammadMattiullah** [iamacup/react-native-markdown-display#59]
Hello people,
Can someone guide me that is it possible to use the code like above:
```
   <Text>
      <Markdown
        onLinkPress={() => alert('Link Clicked')}
        style={{ link: { color: 'blue' } }}
      >
        {body}
      </Markdown>
    </Text>
```
As i need to use this markdown functionality with native text component
@iamacup

**Comment by iamacup** [comment]
Why would you need to do this? are you just trying to render a link with markdown styling inside a component?

If you are, this would work:

```
const copy = `
  [link to google](https://www.google.com/)
`;

const rules = {
    body: (node, children, parent, styles) => children,
    paragraph: (node, children, parent, styles) => children      
};


const App: () => React$Node = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView
          style={{height: '100%', paddingHorizontal: '4%', paddingTop: 20}}
        >
          <Text>
             <Markdown 
              onLinkPress={() => alert('Link Clicked')}
              style={{ link: { color: 'blue' } }}
              rules={rules}
              debugPrintTree
            >
              {copy}
            </Markdown>
          </Text>
        </ScrollView>
      </SafeAreaView>
    </>
  );
};
```

see the `debugPrintTree` argument and the output it makes to understand why this works - i.e. i removes the `View` from the `body` and `paragraph` and just returns the children directly. it will still be wrapped in additional `Text` components at `textgroup`, `link` and `text` in the render hierarchy though so you might want to remove them if you need to.
