### ISSUE TITLE
Successive LineBreaks 

### ISSUE THREAD

**Issue by MuhammadMattiullah** [iamacup/react-native-markdown-display#62]
@iamacup Thankyou for ur response!
```
const rules = {
  body: (node, children, parent, styles) => children,
  paragraph: (node, children, parent, styles) => children,
};

export const MarkdownText = ({ body, onLinkPress }) => (
  <Markdown
    markdownit={
      MarkdownIt({ typographer: true, linkify: true,breaks: true,
      }).disable(['blockquote', 'list', 'code'])
    }
    onLinkPress={(url) => onLinkPress(url)}
    style={{ link: { color: '#007BC7' } }}
    rules={rules}
  >
    {body}
  </Markdown>
);
```
This is the code block.
I want to handle multiple successive linebreaks in this scenario. Kindly guide me how can i achieve this.
Markdown is not displaying multiple linebreaks and ignoring multiple linebreaks during rendering

_Originally posted by @MuhammadMattiullah in https://github.com/iamacup/react-native-markdown-display/issues/49#issuecomment-603129562_

**Comment by tomeberle** [comment]
Same issue here

**Comment by iamacup** [comment]
Hey, sorry this has been slow.

your first question on https://github.com/iamacup/react-native-markdown-display/issues/49 was about all line breaks not working which was not the correct place for it, but https://github.com/iamacup/react-native-markdown-display/issues/49 is actually about this same issue you are describing here

I am going to close this one, and put it on the 6.1.0 - and take a look at it soon.
