### ISSUE TITLE
How to reduce line spacing in bullet list

### ISSUE THREAD

**Issue by KSergey65** [iamacup/react-native-markdown-display#63]
Hi,

I have list:
```
- item 1
- item 2
- item 3
```

I need some help with styles:  
I want reduce line spacing in bullet list

I try to modify styles `bullet_list` and `bullet_list_content`
I can’t change the distance between the lines...

how to I can change spacing in bullet list?

thank you!

**Comment by TwR-Slice** [comment]
Have the same Problem. There seems to be a padding or something that can't be removed with any styles I tried.

**Comment by iamacup** [comment]
So, theres a couple of things going on here, you have to remember to use the `debugPrintTree` to see how the tree is rendered and what elements are effecting the styles.

markdown-it returns the bullet list with children that are actually paragraph and text element like this:

```
-bullet_list
--list_item
---paragraph
----textgroup
-----text
```

So in fact, to reduce the height of the bullet points you also need to fiddle with the paragraph - like this:

```
const copy = `
Here is a line of text

- item 1
- item 2
- item 3

Here is another line of text
`;

const styles = {
  paragraph: {
    marginTop: 0,
    marginBottom: 0,
  },
  bullet_list_icon: {
    lineHeight: 0,
  }
};

const App: () => React$Node = () => {
  return (
    <>
      <SafeAreaView>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={{height: '100%'}}>
          <View style={{height: '100%', padding: 10}}>
            <Markdown 
              debugPrintTree
              style={styles}
            >
              {copy}
            </Markdown>
          </View>
        </ScrollView>
      </SafeAreaView>
    </>
  );
};
```

But this has the nasty side effect of ballsing up paragraphs:

![image](https://user-images.githubusercontent.com/12894620/78078771-bc57fa80-73a2-11ea-8d9d-620f00467b9f.png)

I am going to consider this as part of a wider style change to fix lists and their styling in general - but to stop this effecting both lists and normal paragraphs we have to make a new paragraph render rule like this:

```
const copy = `
Here is a line of text

- item 1
- item 2
- item 3

Here is another line of text
`;

const styles = {
  paragraph_list: {
    marginTop: 0,
    marginBottom: 0,
  },
  bullet_list_icon: {
    lineHeight: 0,
  }
};

const rules = {
  paragraph: (node, children, parent, styles) => {
    if(parent[0].type === 'list_item') {
      return (
        <View key={node.key} style={styles._VIEW_SAFE_paragraph_list}>
          {children}
        </View>
      );
    }

    return (
      <View key={node.key} style={styles._VIEW_SAFE_paragraph}>
        {children}
      </View>
    );
  }
}

const App: () => React$Node = () => {
  return (
    <>
      <SafeAreaView>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={{height: '100%'}}>
          <View style={{height: '100%', padding: 10}}>
            <Markdown 
              debugPrintTree
              style={styles}
              rules={rules}
            >
              {copy}
            </Markdown>
          </View>
        </ScrollView>
      </SafeAreaView>
    </>
  );
};
```

![image](https://user-images.githubusercontent.com/12894620/78080029-486b2180-73a5-11ea-8ad5-caf8eed34a1a.png)

**Comment by iamacup** [comment]
going to close, feel free to open if further q's
