### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by kalicki** [iamacup/react-native-markdown-display#66]
Hey!

I use `markdown-it-emoji` it creates a type called `emoji` so I create custom rule, example:

```
emoji: (node, children, parent) => {
			return (
				<Text key={node.key} style={styles.emoji} numberOfLines={numberOfLines}>
					{node.content}
				</Text>
			)
		},
```

What I wanted to apply is a unique style for emojis when there is only emoji (and other non-strings).

Example: 
`;) ;) ;)` -> Only Emoji
`;)` -> Only Emoji
`;) lorem` -> Paragraph
`;) ipsum` -> Paragraph
🔢  -> only Emoji
🔢 lorem -> Paragraph

There is another case that I pass in the markdown is that the emoji already formatted can arrive and I would like it to pass the right rule (type: emoji) and not the paragraph.

I have this:
```
const renderOnlyEmoji = (key, text) => (
		<Text key={key} style={styles.emoji} numberOfLines={numberOfLines}>
			{text}
		</Text>
	)

	const rules = {
		emoji: (node, children, parent) => {
			if (this.isOnlyEmoji(node.content)) { // <- if I could get the formatted emoji here, it will work
				return renderOnlyEmoji(node.key, node.content)
			}

			return (
				<Text key={node.key} style={styles.text} numberOfLines={numberOfLines}>
					{node.content}
				</Text>
			)
		},
		paragraph: (node, children, parent) => {
			if (this.isOnlyEmoji(message.txt)) {
				return renderOnlyEmoji(node.key, message.txt)
			}

			return (
				<Text key={node.key} style={styles.text} numberOfLines={numberOfLines}>
					{children}
				</Text>
			)
		}
}

...

<Markdown
					rules={rules}
					style={styles}
					mergeStyle={true}
					markdownit={...}
				>
					{message.txt}
				</Markdown>
```

**Comment by kalicki** [comment]
ping to @iamacup

**Comment by iamacup** [comment]
Sorry buddy this one has completely slipped past me thanks for the nudge ;-)

can you print out the element hierarchy with the `debugPrintTree` prop

```
<Markdown debugPrintTree> ... </Markdown>
```

Let's check that the plugin is working properly, and what rule name(s) it is assigning the emoji stuff to and in what order - then it will maybe be easier to see how to make it work

**Comment by kalicki** [comment]
hahaha no problem 

I use version `4.0.11` it doesn't seem to work, does not seem to work, I will try to update and analyze

**Comment by kalicki** [comment]
Cool, it's working ... I think it's a bit complex to check if each message has only emoji, knowing that a structure is generated below

```
;) ;) ;)

body
-paragraph
--textgroup
---emoji
---text
---emoji
 ---text
---emoji
```
- - -

```
;) lorem

body
-paragraph
--textgroup
---emoji
---text
```

- - - 

```
🔢 

body
-paragraph
--textgroup
---text
```

**Comment by iamacup** [comment]
so it looks like markdown-it-emoji does not pick up already formatted emoji's - what you will have to do is either see if you can make that library pick them up or you will need to use something like https://github.com/mathiasbynens/emoji-regex and rewrite the paragraph rule to detect >textgroup>text containing an emoji and return your other rule - a bit of a pain i know!

**Comment by kalicki** [comment]
Ah right!

i already have it:
```
isOnlyEmoji(message) {
		if (!message || !message.trim()) {
			return false
		}

		return message.replace(emojiRegex(), '').trim() === ''
	}
```

--- 
```
paragraph: (node, children, parent) => {
			if (this.isOnlyEmoji(message.txt)) {
				return renderOnlyEmoji(node.key, message.txt)
			}

			return (
				<Text key={node.key} style={styles.text} numberOfLines={numberOfLines}>
					{children}
				</Text>
			)
		},
```

The problem is in the markdown, I want to detect `onlyEmoji` in the markdown, example
```
;) ;) -> this should be emoji only and enter `renderOnlyEmoji` to apply specific styles for when there is only emoji
```

**Comment by iamacup** [comment]
Let me have a little play tomorrow, need to hit the sack right now!

**Comment by kalicki** [comment]
Example
<img width="398" alt="Screen Shot 2020-04-20 at 19 32 28" src="https://user-images.githubusercontent.com/3674885/79806286-6b527b00-833e-11ea-8070-cacddd127f78.png">

The idea is that when there is only emoji it has different styles leaving the emojis with different height when I get formatted I can handle it, when I get it via markdown that's the problem.


Green is right and red is complicated. When you have emoji + text you are right... in short the idea is that 1 resembles 3 and 4

**Comment by kalicki** [comment]
Hey @iamacup, any news?

**Comment by iamacup** [comment]
Hey, really sorry about this, a million things came up recently - are you still working on this and still need help?

**Comment by kalicki** [comment]
Hey

I gave a bypass for not finding a smart solution, but soon I must get back to that...

**Comment by iamacup** [comment]
I think i am going to close this one - as it's unlikely any changes will be made to the core library and instead to solve this is going to involve a bunch of either

1. annoying specific render rules or;
2. a custom AST parser

which won't ship with RNMD

Good luck!
