### ISSUE TITLE
Can I have markdown as a list?

### ISSUE THREAD

**Issue by ghost** [iamacup/react-native-markdown-display#71]
I am concern about performance.

Will this package renders the marked texts as a loop or it parse from string ??

because if there the marked text renders as loop then may affect on performance, please someone help me and sure how this package works.

**Comment by iamacup** [comment]
The input text is passed through [markdown-it](https://github.com/markdown-it/markdown-it) (using the`markdownIt.parse`) which spits out a nested array of objects that represent the items to render.

This is itterated over and displayed - `o(n)`
