### ISSUE TITLE
onLinkPressed is not a prop on Markdown component

### ISSUE THREAD

**Issue by pke** [iamacup/react-native-markdown-display#73]
Somehow the docs claim that overriding links click can be done via setting `onLinkPressed`. However this prop is not exposed on the Markdown props.

**Comment by iamacup** [comment]
I don't understand this issue mate, you will need to provide much more info.

I just tried the example in the docs and its working with a couple of tweaks to fix the depricated / changed PureComponent.

I have slightly tweaked the docs to change to functional component in the example.

**Comment by pke** [comment]
I am sorry, I was unclear, that the typescript definitions don't include the `onLinkPressed` as prop of the `Markdown` component.
![image](https://user-images.githubusercontent.com/164625/83686305-45312380-a5ea-11ea-83d7-3af1b8ecabaa.png)

And that is also evident when one looks at https://github.com/iamacup/react-native-markdown-display/blob/master/src/index.d.ts#L86

I have created https://github.com/iamacup/react-native-markdown-display/pull/74 to fix this.
