### ISSUE TITLE
Remove default padding and margin from a markdown component

### ISSUE THREAD

**Issue by kobimilan995** [iamacup/react-native-markdown-display#75]
I'm using this library to display markdown format text, and it is inserting unnecessarry paddings/margins on top and bottom. Is there any way to remove those?

**Comment by iamacup** [comment]
please provide a full code example

**Comment by kobimilan995** [comment]
![Screenshot 2020-06-09 at 20 42 04](https://user-images.githubusercontent.com/31390546/84187062-c7f62a80-aa91-11ea-9b37-5278420095eb.png)
![Screenshot 2020-06-09 at 20 42 02](https://user-images.githubusercontent.com/31390546/84187069-caf11b00-aa91-11ea-9a7f-ff1d86f62231.png)
![Screenshot 2020-06-09 at 20 41 40](https://user-images.githubusercontent.com/31390546/84187072-cb89b180-aa91-11ea-9cfd-c03ca82f5f9e.png)

**Comment by kobimilan995** [comment]
Actually its not padding, its some container that has bigger height then the text. I really need to remove it

**Comment by kobimilan995** [comment]
![Screenshot 2020-06-09 at 20 43 57](https://user-images.githubusercontent.com/31390546/84187188-fa078c80-aa91-11ea-86f5-232d8a4116d5.png)
![Screenshot 2020-06-09 at 20 44 02](https://user-images.githubusercontent.com/31390546/84187191-fb38b980-aa91-11ea-9a67-ceb24236e5f0.png)

**Comment by kobimilan995** [comment]
`<Markdown onLinkPress={() => true}>{'Some text'}</Markdown>`

**Comment by kobimilan995** [comment]
Really basic usage. The above screenshot is when i use inspector tool on a single line of markdown text

**Comment by iamacup** [comment]
You need to look at what is actually being rendered

If you use the `debugPrintTree` property (docs in readme) you will see what rules are being used.

effectively a parahraph is being created, you will need to remove the padding / margin on that container with the styles for the relevant rules printed by `debugPrintTree`

https://github.com/iamacup/react-native-markdown-display/blob/master/src/lib/styles.js
