### ISSUE TITLE
Invalid prop `markdownit` of type `MarkdownIt`

### ISSUE THREAD

**Issue by kopax** [iamacup/react-native-markdown-display#76]
On the web, ios and android (all together):

    <MarkdownDisplay
      rules={rules}
      markdownit={MarkdownIt({
        linkify: true,
        typographer: true
      })}
      {...rest}
    />

This cause:

    index.js:1 Warning: Failed prop type: Invalid prop `markdownit` of type `MarkdownIt` supplied to `<<anonymous>>`, expected instance of `MarkdownIt`.

**Comment by iamacup** [comment]
Can you show me how you are importing MarkdownIt in this context please

**Comment by kopax** [comment]
```js
import Markdown from 'react-native-markdown-display';
import MarkdownIt from 'markdown-it';
```

I have tried with `new` and it didn't help, I checked the exported default function and it create the instance so new is not necessary. I am not using typescript so I have no clue why it fail.

I believe this can be tested on snack.io quite easily.

**edit** this error is a no go, but if it can be solved I will prefer to use your markdown processor than the react native simple markdown that is not rendering list spaces correctly and it break my ios app.

Side note: It would be nice to be able to whitelist what we want instead of ignoring

**Comment by iamacup** [comment]
I don't know why the check is not passing, i don't know enough about the instanceof operator in PropTypes / JS Core. Note this is not related to TypeScript it is the PropTypes check failing and **I cant reproduce it**

The only thing i can think of is that your markdown-it in package.json is resolving to a diff version than the lib (possible)

Try this:

`import Markdown, {MarkdownIt} from 'react-native-markdown-display';`

internally we just do `markdownit: PropTypes.instanceOf(MarkdownIt),` where `MarkdownIt` is just `import MarkdownIt from 'markdown-it';` as seen here: https://github.com/iamacup/react-native-markdown-display/blob/master/src/index.js

re whitelist you will have to see how markdown-it handles - https://github.com/markdown-it/markdown-it/issues/620

**Comment by kopax** [comment]
- By using `import MarkdownIt from 'markdown-it';` the error exist.
- By using `import Markdown, {MarkdownIt} from 'react-native-markdown-display';` the error disappear.

I am testing in all environments now and WOW, it's an excellent work, well-deserved star ! Thank you so much Cup!
