### ISSUE TITLE
Newlines in table columns via <br> not possible

### ISSUE THREAD

**Issue by andrekovac** [iamacup/react-native-markdown-display#83]
In traditional Markdown `html` can be sprinkled here and there to get some behavior which isn't available with Markdown commands.

A thing I recently needed was the ability to force line-breaks inside table columns. [This SO article](https://stackoverflow.com/questions/11700487/newline-in-markdown-table) suggests to use `<br>`. This also works in Markdown but does not in this library.

**Comment by iamacup** [comment]
I expect this is related to https://github.com/iamacup/react-native-markdown-display/issues/49 which i also don't have a solution for - i will take a look at this again when i get a chance

**Comment by iamacup** [comment]
Had a litttle look at this - code below - you will need to deal with the fact that HTML is enabled - things like `<a>` will work etc. but won't link to anything without modificatioon to the `html_inline` rule (perhaps this is fine behavior)

![image](https://user-images.githubusercontent.com/12894620/86511596-93586300-bdf2-11ea-9d98-da64f551097d.png)


```jsx
import React from 'react';
import { SafeAreaView, ScrollView, StatusBar, Text } from 'react-native';

import Markdown, { MarkdownIt, hasParents } from 'react-native-markdown-display';

const markdownItInstance = MarkdownIt({typographer: true, html: true});

const copy = `
Top one
<br>
<br>
<br>
Bottom one

 | Option | Description |
 | ------ | ----------- |
 | data   | path to data files to supply the data<br><br><br>that will be passed into templates. <br><br><br><br> cool.|
`;

const rules = {
  html_inline:(node, children, parent, styles) => {
    // we check that the parent array contans a td because <br> in paragraph setting will create a html_inlinde surrounded by a soft break, try removing the clause to see what happens (double spacing on the <br> between 'top one' and 'bottom one')
    if(node.content.trim() === '<br>' && hasParents(parent, 'td')) {
      return <Text key={node.key}>{'\n'}</Text>
    }

    return null;
  }
}

const App: () => React$Node = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={{height: '100%'}}
        >
            <Markdown
              rules={rules}
              markdownit={markdownItInstance}
              debugPrintTree
            >
              {copy}
            </Markdown>
        </ScrollView>
      </SafeAreaView>
    </>
  );
};

export default App;
```

**Comment by moeezDevelo** [comment]
@iamacup You saved my day. Thanks!!
