### ISSUE TITLE
How can I make the text fit the viewport?

### ISSUE THREAD

**Issue by kopax** [iamacup/react-native-markdown-display#84]
With the following `content` variable:
```
const content = `voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture voiture`;
```

Using `<Text />`:

```jsx
<Text>{content}</Text>
```

![image](https://user-images.githubusercontent.com/1866564/86280670-86622680-bbdc-11ea-95c7-61bcc32cc0dc.png)

Using `<Markdown />`:

```jsx
<Markdown>{content}</Markdown>
```

![image](https://user-images.githubusercontent.com/1866564/86280725-a396f500-bbdc-11ea-9184-fb127bafbd45.png)

**Comment by kopax** [comment]
Solved with:

```diff
    <Markdown
+      style={{
+        body: { flex: 1 },
+      }}
      {...rest}
    />
```

perhaps this could be the default since it's for react-native and web and they do not behave the same ?

**Comment by iamacup** [comment]
You are right, this probably should be the default, let me have a think because i think this would clasify as a major change as it could break things for a lot of people that rely on current state of things

**Comment by kopax** [comment]
It's ok to break think, just use a major version bump. Be careful, I have experienced strange issues with react-native-markdown-display, I had to use `wordBreak: 'word-wrap` in many view for the web in order to get the text visible in the view port on the web, but now I get react-native complaining about it in the web since `View` should not use `wordBreak`.

**Comment by iamacup** [comment]
do you have a project using react-native web that requires wordBreak that i can take a look at?

**Comment by oleksiipopovych** [comment]
I had a similar issue with the ordered list `style={{
        textgroup: {
     width: '100%'
    },
 }}` fixed the issue.

**Comment by droplessjordan** [comment]
Having the same issue. Markdown text isn't wrapping to fix the space its in?
