### ISSUE TITLE
Screen reader announces bullet point for unordered list as "dot" after reading list item text

### ISSUE THREAD

**Issue by Katedam** [iamacup/react-native-markdown-display#98]
This is easily fixed by adding `accessible={false}` to the `Text` component that displays the dot. All `Text` components are accessible by default but there's no need for a screen reader to announce the dot in this case. 

```
<Text style={[modifiedInheritedStylesObj, styles.bullet_list_icon]} accessible={false}>
        {Platform.select({
              android: '\u2022',
              ios: '\u00B7',
              default: '\u2022',
        })}
</Text>
```

I image that if you used a `FlatList` instead of a `View` then it would be even more accessible as a semantic list but the above suggestion would at least make it less confusing and verbose for the time being.

I am happy to contribute and open a PR for this if you like...

**Comment by iamacup** [comment]
Hey, this all sounds great, if you wouldn't mind writing the pull request i will merge :)

**Comment by Katedam** [comment]
> Hey, this all sounds great, if you wouldn't mind writing the pull request i will merge :)

Awesome! Pull Request opened! 🙏
